module pipeline_id (
    input         clk,
    input         rst,
    input  [31:0] id_instruction,
    input  [63:0] id_pc, id_pc4,
    // wb feedback
    input  [4:0]  wb_rd,
    input  [63:0] wb_write_data,
    input         wb_RegWrite,
    // control outputs
    output        id_RegWrite, id_MemRead, id_MemWrite,
    output [1:0]  id_MemToReg, id_ALUOp, id_ALUSrcA,
    output        id_ALUSrc, id_Branch, id_Jump,
    output        id_is_csr, id_is_mret, id_is_32bit,
    // data outputs
    output [63:0] id_rs1_data, id_rs2_data, id_immediate,
    output [4:0]  id_rs1, id_rs2, id_rd,
    output [2:0]  id_funct3,
    output [6:0]  id_funct7,
    output [11:0] id_funct12,
    output [63:0] id_pc_out, id_pc4_out
);
    assign id_pc_out  = id_pc;
    assign id_pc4_out = id_pc4;
    assign id_rd      = id_instruction[11:7];
    assign id_funct3  = id_instruction[14:12];
    assign id_rs1     = id_instruction[19:15];
    assign id_rs2     = id_instruction[24:20];
    assign id_funct7  = id_instruction[31:25];
    assign id_funct12 = id_instruction[31:20];

    // jump is dynamically generated by control_unit

    control_unit u_ctrl (
        .opcode   (id_instruction[6:0]),
        .funct3   (id_funct3),
        .funct12  (id_funct12),
        .RegWrite (id_RegWrite),
        .MemRead  (id_MemRead),
        .MemWrite (id_MemWrite),
        .MemtoReg (id_MemToReg),
        .ALUSrc   (id_ALUSrc),
        .ALUSrcA  (id_ALUSrcA),
        .Branch   (id_Branch),
        .Jump     (id_Jump),
        .ALUOp    (id_ALUOp),
        .is_csr   (id_is_csr),
        .is_mret  (id_is_mret),
        .is_32bit (id_is_32bit)
    );

    wire [63:0] rf_read_data1, rf_read_data2;

    register_file u_regfile (
        .clk        (clk),
        .rst        (rst),
        .rs1        (id_rs1),
        .rs2        (id_rs2),
        .rd         (wb_rd),
        .write_data (wb_write_data),
        .reg_write  (wb_RegWrite),
        .read_data1 (rf_read_data1),
        .read_data2 (rf_read_data2)
    );

    // WB->ID bypass for same-cycle write/read hazards.
    assign id_rs1_data = (wb_RegWrite && (wb_rd != 5'b0) && (wb_rd == id_rs1))
                       ? wb_write_data : rf_read_data1;
    assign id_rs2_data = (wb_RegWrite && (wb_rd != 5'b0) && (wb_rd == id_rs2))
                       ? wb_write_data : rf_read_data2;

    immediate_generator u_immgen (
        .instruction (id_instruction),
        .immediate   (id_immediate)
    );
endmodule
