// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"
class Vtop_cla_64b;


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final {
  public:
    // CELLS
    Vtop_cla_64b* __PVT__soc_top__DOT__u_core__DOT__u_if__DOT__u_pc4__DOT__adder_inst;
    Vtop_cla_64b* __PVT__soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__cla_inst;
    Vtop_cla_64b* __PVT__soc_top__DOT__u_core__DOT__u_ex__DOT__u_bta__DOT__adder_inst;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(buttons,7,0);
        VL_OUT8(leds,7,0);
        VL_OUT8(vga_hsync,0,0);
        VL_OUT8(vga_vsync,0,0);
        VL_OUT8(vga_r,3,0);
        VL_OUT8(vga_g,3,0);
        VL_OUT8(vga_b,3,0);
        VL_OUT8(spi_sck,0,0);
        VL_OUT8(spi_mosi,0,0);
        VL_IN8(spi_miso,0,0);
        VL_OUT8(spi_cs_n,0,0);
        VL_OUT8(dbg_vga_we,0,0);
        CData/*0:0*/ soc_top__DOT__clk;
        CData/*0:0*/ soc_top__DOT__rst;
        CData/*7:0*/ soc_top__DOT__buttons;
        CData/*7:0*/ soc_top__DOT__leds;
        CData/*0:0*/ soc_top__DOT__vga_hsync;
        CData/*0:0*/ soc_top__DOT__vga_vsync;
        CData/*3:0*/ soc_top__DOT__vga_r;
        CData/*3:0*/ soc_top__DOT__vga_g;
        CData/*3:0*/ soc_top__DOT__vga_b;
        CData/*0:0*/ soc_top__DOT__spi_sck;
        CData/*0:0*/ soc_top__DOT__spi_mosi;
        CData/*0:0*/ soc_top__DOT__spi_miso;
        CData/*0:0*/ soc_top__DOT__spi_cs_n;
        CData/*0:0*/ soc_top__DOT__dbg_vga_we;
        CData/*0:0*/ soc_top__DOT__dmem_read_req;
        CData/*0:0*/ soc_top__DOT__dmem_write_req;
        CData/*2:0*/ soc_top__DOT__dmem_funct3;
        CData/*0:0*/ soc_top__DOT__ram_read_req;
        CData/*0:0*/ soc_top__DOT__ram_write_req;
        CData/*2:0*/ soc_top__DOT__ram_funct3;
        CData/*0:0*/ soc_top__DOT__vga_read_req;
        CData/*0:0*/ soc_top__DOT__vga_write_req;
        CData/*2:0*/ soc_top__DOT__vga_funct3;
        CData/*0:0*/ soc_top__DOT__io_read_req;
        CData/*0:0*/ soc_top__DOT__io_write_req;
        CData/*7:0*/ soc_top__DOT__io_address;
        CData/*2:0*/ soc_top__DOT__io_funct3;
        CData/*0:0*/ soc_top__DOT__clint_read_req;
        CData/*0:0*/ soc_top__DOT__clint_write_req;
        CData/*3:0*/ soc_top__DOT__clint_address;
        CData/*0:0*/ soc_top__DOT__timer_interrupt;
        CData/*0:0*/ soc_top__DOT__spi_read_req;
        CData/*0:0*/ soc_top__DOT__spi_write_req;
        CData/*3:0*/ soc_top__DOT__spi_address;
        CData/*1:0*/ soc_top__DOT__clk_div;
        CData/*0:0*/ soc_top__DOT__clk_25mhz;
        CData/*7:0*/ soc_top__DOT__led_reg;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__dmem_read_req;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__dmem_write_req;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__dmem_funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__timer_interrupt;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__pc_stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__if_id_stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_ex_stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__if_id_flush_ext;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_ex_flush_ext;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_mem_flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__multdiv_busy;
    };
    struct {
        CData/*1:0*/ soc_top__DOT__u_core__DOT__ForwardA;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__ForwardB;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__id_MemToReg;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__id_ALUOp;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__id_ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_ALUSrc;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_Jump;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__id_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__id_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__id_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__id_funct3;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__id_funct7;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_is_32bit;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__ex_MemToReg;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__ex_ALUOp;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__ex_ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_ALUSrc;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_Jump;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__ex_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__ex_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__ex_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__ex_funct3;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__ex_funct7;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_is_32bit;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_alu_zero;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__ex_branch_taken;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mstatus_mie;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mie_mtie;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__trap_pending;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__take_trap;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__trap_flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mem_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mem_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mem_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__mem_MemToReg;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mem_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mem_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__mem_alu_zero;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__mem_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__mem_funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__wb_RegWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__wb_MemToReg;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__wb_rd;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__id_opcode;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__id_uses_rs2;
        CData/*0:0*/ soc_top__DOT__u_core__DOT____VdfgRegularize_h19c8320d_0_0;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__ex_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__ex_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__mem_rd;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__wb_rd;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__mem_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__wb_RegWrite;
    };
    struct {
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__ForwardA;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_forwarding__DOT__ForwardB;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__ex_MemRead;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__ex_rd;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__id_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__id_rs2;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__id_uses_rs2;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__multdiv_busy;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__pc_stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__if_id_stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__id_ex_stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__id_ex_flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__ex_mem_flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__rs1_hazard;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__rs2_hazard;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_hazard__DOT__load_use_hazard;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_pc__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_pc__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_pc__DOT__en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_if__DOT__u_pc4__DOT__cout;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_if__DOT__u_pc4__DOT__carry_into_msb;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__rst;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__wb_rd;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__wb_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_MemToReg;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_ALUOp;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_ALUSrc;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_is_32bit;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_funct3;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_funct7;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT____VdfgRegularize_hf18c6620_0_0;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__opcode;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__MemRead;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__MemtoReg;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__ALUOp;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__MemWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__ALUSrc;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__is_32bit;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__rst;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__rs1;
    };
    struct {
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__rd;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__reg_write;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__zero_flag;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_immgen__DOT__opcode;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__stall;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_MemToReg;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_ALUOp;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_ALUSrc;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_is_32bit;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_funct3;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_funct7;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_MemToReg;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_ALUOp;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_ALUSrc;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_is_32bit;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_funct3;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_funct7;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__rst;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_rs1;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_rs2;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_funct3;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_funct7;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_ALUSrc;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_ALUOp;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_ALUSrcA;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_is_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_is_32bit;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__timer_interrupt;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__take_trap;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ForwardA;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ForwardB;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_alu_zero;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_branch_taken;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__multdiv_busy;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__mstatus_mie;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__mie_mtie;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_ctrl;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__is_m_ext;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__is_csr_rs_rc;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__csr_write_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__csr_read_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__is_jalr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__branch_cond;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALUOp;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__funct7_bit5;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__funct3;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALUControl;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__opcode;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__cout;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__carry_flag;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__overflow_flag;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__zero_flag;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__addsub_cout;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__addsub_overflow;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__sub_sel;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__sub;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__cout;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__overflow;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__carry_into_msb;
        CData/*5:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__shamt;
        CData/*5:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__shamt;
        CData/*5:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__shamt;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__rs1_sign;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__rs2_sign;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__signs_different;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__rs1_less_rs2_unsigned;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__rs1_less_rs2_signed;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sltu__DOT__less_unsigned;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__is_m_ext;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__busy;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__state;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__csr_write;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__csr_read;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__timer_interrupt;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__take_trap;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__is_mret;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mstatus_mie;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mie_mtie;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_bta__DOT__cout;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_bta__DOT__carry_into_msb;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__flush;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_MemToReg;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_alu_zero;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_funct3;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_RegWrite;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_MemWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_MemToReg;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_Branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_Jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_alu_zero;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_rd;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__mem_MemRead;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__mem_MemWrite;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__mem_funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__dmem_read_req;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__dmem_write_req;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__dmem_funct3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__mem_RegWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__mem_MemToReg;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__mem_rd;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__wb_RegWrite;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__wb_MemToReg;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__wb_rd;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_wb__DOT__wb_MemToReg;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__reset;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__dmem_read_req;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__dmem_write_req;
        CData/*2:0*/ soc_top__DOT__u_bus__DOT__dmem_funct3;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__ram_read_req;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__ram_write_req;
        CData/*2:0*/ soc_top__DOT__u_bus__DOT__ram_funct3;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__vga_read_req;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__vga_write_req;
        CData/*2:0*/ soc_top__DOT__u_bus__DOT__vga_funct3;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__spi_read_req;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__spi_write_req;
        CData/*3:0*/ soc_top__DOT__u_bus__DOT__spi_address;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__clint_read_req;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__clint_write_req;
        CData/*3:0*/ soc_top__DOT__u_bus__DOT__clint_address;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__io_read_req;
        CData/*0:0*/ soc_top__DOT__u_bus__DOT__io_write_req;
        CData/*7:0*/ soc_top__DOT__u_bus__DOT__io_address;
        CData/*2:0*/ soc_top__DOT__u_bus__DOT__io_funct3;
        CData/*0:0*/ soc_top__DOT__u_ram__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_ram__DOT__reset;
        CData/*0:0*/ soc_top__DOT__u_ram__DOT__dmem_read_req;
        CData/*0:0*/ soc_top__DOT__u_ram__DOT__dmem_write_req;
        CData/*2:0*/ soc_top__DOT__u_ram__DOT__dmem_funct3;
        CData/*0:0*/ soc_top__DOT__u_ram__DOT__use_little_endian;
        CData/*0:0*/ soc_top__DOT__u_clint__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_clint__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_clint__DOT__clint_read_req;
        CData/*0:0*/ soc_top__DOT__u_clint__DOT__clint_write_req;
        CData/*3:0*/ soc_top__DOT__u_clint__DOT__clint_address;
        CData/*0:0*/ soc_top__DOT__u_clint__DOT__timer_interrupt;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__clk;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__read_req;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__write_req;
        CData/*3:0*/ soc_top__DOT__u_spi__DOT__address;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__sck;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__mosi;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__miso;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__cs_n;
        CData/*7:0*/ soc_top__DOT__u_spi__DOT__clk_div;
        CData/*0:0*/ soc_top__DOT__u_spi__DOT__busy;
        CData/*7:0*/ soc_top__DOT__u_spi__DOT__shift_reg;
        CData/*7:0*/ soc_top__DOT__u_spi__DOT__rx_data;
        CData/*2:0*/ soc_top__DOT__u_spi__DOT__state;
        CData/*7:0*/ soc_top__DOT__u_spi__DOT__clk_cnt;
        CData/*2:0*/ soc_top__DOT__u_spi__DOT__bit_cnt;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__clk_cpu;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__cpu_write_req;
        CData/*2:0*/ soc_top__DOT__u_vga__DOT__cpu_funct3;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__clk_25mhz;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__vga_hsync;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__vga_vsync;
        CData/*3:0*/ soc_top__DOT__u_vga__DOT__vga_r;
        CData/*3:0*/ soc_top__DOT__u_vga__DOT__vga_g;
        CData/*3:0*/ soc_top__DOT__u_vga__DOT__vga_b;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__h_sync_raw;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__v_sync_raw;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__video_active;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__in_window;
        CData/*7:0*/ soc_top__DOT__u_vga__DOT__fb_y;
        CData/*7:0*/ soc_top__DOT__u_vga__DOT__vga_pixel_data;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__h_sync_d;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__v_sync_d;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__video_active_d;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__in_window_d;
        CData/*3:0*/ soc_top__DOT__u_vga__DOT__r_out;
        CData/*3:0*/ soc_top__DOT__u_vga__DOT__g_out;
        CData/*3:0*/ soc_top__DOT__u_vga__DOT__b_out;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__clk_25mhz;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__rst;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__h_sync;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__v_sync;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__video_active;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__clk_cpu;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__cpu_write_req;
        CData/*2:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__cpu_funct3;
        CData/*0:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__clk_vga;
        CData/*7:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__vga_read_data;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v0;
        CData/*0:0*/ __VdlySet__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v0;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v1;
        CData/*0:0*/ __VdlySet__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v1;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v2;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v3;
        CData/*0:0*/ __VdlySet__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v3;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v4;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v5;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v6;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v7;
        CData/*0:0*/ __VdlySet__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v7;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v8;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v9;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v10;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v11;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v12;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v13;
        CData/*7:0*/ __VdlyVal__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v14;
        CData/*0:0*/ __VstlFirstIteration;
    };
    struct {
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_pc__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_pc__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_if_id__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_if_id__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_id_ex__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_id_ex__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_ex_mem__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_ex_mem__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_mem_wb__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__u_mem_wb__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_ram__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_clint__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_spi__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_vga__DOT__clk_25mhz__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_vga__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_vga__DOT__u_timing__DOT__clk_25mhz__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_vga__DOT__u_timing__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_vga__DOT__u_ram__DOT__clk_cpu__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_vga__DOT__u_ram__DOT__clk_vga__0;
        VL_OUT16(dbg_vga_addr,15,0);
        SData/*15:0*/ soc_top__DOT__dbg_vga_addr;
        SData/*15:0*/ soc_top__DOT__vga_address;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__id_funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__ex_funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_ctrl__DOT__funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_funct12;
        SData/*11:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__csr_addr;
        SData/*15:0*/ soc_top__DOT__u_bus__DOT__vga_address;
        SData/*15:0*/ soc_top__DOT__u_vga__DOT__cpu_address;
        SData/*9:0*/ soc_top__DOT__u_vga__DOT__pixel_x;
        SData/*9:0*/ soc_top__DOT__u_vga__DOT__pixel_y;
        SData/*8:0*/ soc_top__DOT__u_vga__DOT__fb_x;
        SData/*15:0*/ soc_top__DOT__u_vga__DOT__vga_ram_addr;
        SData/*9:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__pixel_x;
        SData/*9:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__pixel_y;
        SData/*9:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__h_count;
        SData/*9:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__v_count;
        SData/*15:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__cpu_address;
        SData/*15:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__vga_address;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v0;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v1;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v2;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v3;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v4;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v5;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v6;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v7;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v8;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v9;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v10;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v11;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v12;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v13;
        SData/*15:0*/ __VdlyDim0__soc_top__DOT__u_vga__DOT__u_ram__DOT__memory__v14;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__imem_instruction;
        IData/*22:0*/ soc_top__DOT__ram_address;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__imem_instruction;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__if_instruction;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__id_instruction;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__if_instruction;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__id_instruction;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_instruction;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__i;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_immgen__DOT__instruction;
        VlWide<4>/*127:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__mul_signed;
        VlWide<4>/*127:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__mul_unsigned;
        VlWide<4>/*127:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__mul_su;
        IData/*22:0*/ soc_top__DOT__u_bus__DOT__ram_address;
        IData/*31:0*/ soc_top__DOT__u_ram__DOT__imem_instruction;
        IData/*22:0*/ soc_top__DOT__u_ram__DOT__dmem_address;
        IData/*22:0*/ soc_top__DOT__u_ram__DOT__pc_idx;
        IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__i;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(dbg_vga_data,63,0);
        QData/*63:0*/ soc_top__DOT__dbg_vga_data;
        QData/*63:0*/ soc_top__DOT__imem_address;
        QData/*63:0*/ soc_top__DOT__dmem_address;
        QData/*63:0*/ soc_top__DOT__dmem_write_data;
        QData/*63:0*/ soc_top__DOT__dmem_read_data_in;
        QData/*63:0*/ soc_top__DOT__ram_write_data;
        QData/*63:0*/ soc_top__DOT__ram_read_data;
        QData/*63:0*/ soc_top__DOT__vga_write_data;
        QData/*63:0*/ soc_top__DOT__vga_read_data;
        QData/*63:0*/ soc_top__DOT__io_write_data;
        QData/*63:0*/ soc_top__DOT__io_read_data;
        QData/*63:0*/ soc_top__DOT__clint_write_data;
        QData/*63:0*/ soc_top__DOT__clint_read_data;
        QData/*63:0*/ soc_top__DOT__spi_write_data;
        QData/*63:0*/ soc_top__DOT__spi_read_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__imem_address;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__dmem_address;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__dmem_write_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__dmem_read_data_in;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__if_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__if_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_rs1_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_pc_out;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__id_pc4_out;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_rs1_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_forwarded_rs2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__ex_branch_target;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__trap_target_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__trap_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__mem_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__mem_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__mem_branch_target;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__mem_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__mem_read_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__wb_read_data;
    };
    struct {
        QData/*63:0*/ soc_top__DOT__u_core__DOT__wb_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__wb_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__wb_write_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__pc_next;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__forward_mem_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__forward_wb_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_pc__DOT__pc_next;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_pc__DOT__pc_current;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if__DOT__if_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if__DOT__if_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if__DOT__u_pc4__DOT__pc_current;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if__DOT__u_pc4__DOT__pc_plus_4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__if_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__if_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__id_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_if_id__DOT__id_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__wb_write_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_rs1_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_pc_out;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__id_pc4_out;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__rf_read_data1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__rf_read_data2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__write_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__read_data1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__read_data2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id__DOT__u_immgen__DOT__immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_rs1_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__id_immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_rs1_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_id_ex__DOT__ex_immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_rs1_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_immediate;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__trap_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__forward_mem_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__forward_wb_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_forwarded_rs2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__ex_branch_target;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__trap_target_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__fwd_rs1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_op_a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__fwd_rs2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_op_b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__multdiv_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_result_raw;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_result_32;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__alu_result_mux;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__csr_rdata;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__csr_write_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__mepc_out;
    };
    struct {
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__mtvec_out;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__bta_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__addsub_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__and_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__or_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__xor_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__sll_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__srl_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__sra_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__slt_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__sltu_res;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_addsub__DOT__use_b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_and__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_and__DOT__b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_and__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_or__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_or__DOT__b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_or__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_xor__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_xor__DOT__b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_xor__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__s1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__s2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__s3;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__s4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__s5;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sll__DOT__s6;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__s1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__s2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__s3;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__s4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__s5;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_srl__DOT__s6;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__s1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__s2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__s3;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__s4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__s5;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sra__DOT__s6;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__rs1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__rs2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_slt__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sltu__DOT__rs1;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sltu__DOT__rs2;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu__DOT__u_sltu__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__a;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__b;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__a_signed;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__b_signed;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__csr_wdata;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__csr_rdata;
    };
    struct {
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__trap_pc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mepc;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mtvec;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mstatus;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mcause;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mie;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_csr__DOT__mscratch;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_bta__DOT__pc_current;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_bta__DOT__offset;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_bta__DOT__branch_target;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_branch_target;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__ex_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_branch_target;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ex_mem__DOT__mem_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__mem_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__mem_rs2_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__mem_read_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__dmem_address;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__dmem_write_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem__DOT__dmem_read_data_in;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__mem_read_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__mem_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__mem_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__wb_read_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__wb_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_mem_wb__DOT__wb_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_wb__DOT__wb_alu_result;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_wb__DOT__wb_read_data;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_wb__DOT__wb_pc4;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_wb__DOT__wb_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__dmem_address;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__dmem_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__dmem_read_data_in;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__ram_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__ram_read_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__vga_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__vga_read_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__spi_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__spi_read_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__clint_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__clint_read_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__io_write_data;
        QData/*63:0*/ soc_top__DOT__u_bus__DOT__io_read_data;
        QData/*63:0*/ soc_top__DOT__u_ram__DOT__imem_address;
        QData/*63:0*/ soc_top__DOT__u_ram__DOT__dmem_write_data;
        QData/*63:0*/ soc_top__DOT__u_ram__DOT__dmem_read_data;
        QData/*63:0*/ soc_top__DOT__u_clint__DOT__clint_write_data;
        QData/*63:0*/ soc_top__DOT__u_clint__DOT__clint_read_data;
        QData/*63:0*/ soc_top__DOT__u_clint__DOT__mtime;
        QData/*63:0*/ soc_top__DOT__u_clint__DOT__mtimecmp;
        QData/*63:0*/ soc_top__DOT__u_spi__DOT__write_data;
        QData/*63:0*/ soc_top__DOT__u_spi__DOT__read_data;
        QData/*63:0*/ soc_top__DOT__u_vga__DOT__cpu_write_data;
        QData/*63:0*/ soc_top__DOT__u_vga__DOT__cpu_read_data;
        QData/*63:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__cpu_write_data;
        QData/*63:0*/ soc_top__DOT__u_vga__DOT__u_ram__DOT__cpu_read_data;
        VlUnpacked<QData/*63:0*/, 32> soc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__registers;
        VlUnpacked<CData/*7:0*/, 8388608> soc_top__DOT__u_ram__DOT__memory;
        VlUnpacked<CData/*7:0*/, 65536> soc_top__DOT__u_vga__DOT__u_ram__DOT__memory;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
    };
    struct {
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<QData/*63:0*/, 32>, false, QData/*63:0*/, 1> __VdlyCommitQueuesoc_top__DOT__u_core__DOT__u_id__DOT__u_regfile__DOT__registers;

    // INTERNAL VARIABLES
    Vtop__Syms* vlSymsp;
    const char* vlNamep;

    // PARAMETERS
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_ADD = 0U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_SLL = 1U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_SLT = 2U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_SLTU = 3U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_XOR = 4U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_SRL = 5U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_OR = 6U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_AND = 7U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_SUB = 8U;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_SRA = 0x0dU;
    static constexpr CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_alu_ctrl__DOT__ALU_INV = 0x0fU;
    static constexpr CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__IDLE = 0U;
    static constexpr CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__CALC1 = 1U;
    static constexpr CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__CALC2 = 2U;
    static constexpr CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ex__DOT__u_multdiv__DOT__CALC3 = 3U;
    static constexpr CData/*2:0*/ soc_top__DOT__u_spi__DOT__IDLE = 0U;
    static constexpr CData/*2:0*/ soc_top__DOT__u_spi__DOT__SETUP = 1U;
    static constexpr CData/*2:0*/ soc_top__DOT__u_spi__DOT__HIGH = 2U;
    static constexpr CData/*2:0*/ soc_top__DOT__u_spi__DOT__LOW = 3U;
    static constexpr CData/*2:0*/ soc_top__DOT__u_spi__DOT__DONE = 4U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__H_DISPLAY = 0x00000280U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__H_FRONT = 0x00000010U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__H_SYNC = 0x00000060U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__H_BACK = 0x00000030U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__H_TOTAL = 0x00000320U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__V_DISPLAY = 0x000001e0U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__V_FRONT = 0x0000000aU;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__V_SYNC = 2U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__V_BACK = 0x00000021U;
    static constexpr IData/*31:0*/ soc_top__DOT__u_vga__DOT__u_timing__DOT__V_TOTAL = 0x0000020dU;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* namep);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
